name: neon_chat
description: Der NEON-Chat.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Code generation
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  # Features
  rxdart: ^0.27.3
  intl: ^0.17.0
  equatable: ^2.0.3
  google_maps_flutter: ^2.1.3
  wechat_assets_picker: ^7.0.5
  wechat_camera_picker: ^3.0.2
  woozy_search: ^2.0.3
  scroll_to_index: ^2.1.1
  record: ^3.0.3
  animator: ^3.1.0
  flutter_animator: ^3.2.1
  just_audio: ^0.9.20
  flutter_chat_types: ^3.3.1

  # Dependency Injection
  get_it: ^7.2.0

  # Cache
  # hive: ^2.1.0
  # hive_flutter: ^1.1.0

  # Firebase
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.12

  # State
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  # Functional Programming
  dartz: ^0.10.1

  # Widgets
  badges: ^2.0.2
  file_picker: ^4.5.1
  stop_watch_timer: ^1.3.1
  focused_menu: ^1.0.5
  auto_size_text_pk: ^3.0.0
  visibility_detector: ^0.2.2
  linkwell: ^2.0.6
  flutter_link_previewer: ^2.6.3
  video_thumbnail: ^0.4.6
  flutter_styled_toast: ^2.0.0
  better_player: ^0.0.82
  another_xlider: ^1.0.1+2
  chewie: ^1.3.1
  keyboard_dismisser: ^2.0.1
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0



dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  freezed: ^1.1.1
  bloc_test: ^9.0.2
  hive_generator: ^1.1.2
  test: ^1.20.2

flutter:
